Added priority parameter
sardok/aiogear pull request #5
Opened 2018-06-27 14:36 UTC by agronick

Hey, I added the ability to set an optional priority parameter on each job in the callback client.

2018-07-02 11:56 UTC, sardok requested changes

2018-07-02 11:56 UTC, sardok commented on aiogear/callback_client.py
> -        async def submit_each(uuid, data):
I think its better to have it as parameter with default.
```
async def submit_each(uuid, data, priority=PACKET_TYPES.SUBMIT_JOB):
 ...
```

2018-07-02 11:56 UTC, sardok commented on aiogear/callback_client.py
Following if/elif/else checks could be replace by more idiomatic code like,

```
priority_map = {
    PACKET_TYPES.SUBMIT_JOB_HIGH: self.submit_job_high
    PACKET_TYPES.SUBMIT_JOB_LOW: self.submit_job_low
    PACKET_TYPES.SUBMIT_JOB: self.submit_job
}

submit_funct = priority_map.get(priority)
if not submit_funct:
    raise Exception("Unsupported priority {}".format(priority))
```

2018-07-02 11:58 UTC, sardok commented
@agronick sorry for late reply Kyle, i've just had a time to review the PR.

2018-07-09 23:34 UTC, agronick commented
Thanks Ill make the changes tomorrow.

On Mon, Jul 2, 2018, 7:58 AM Sinan Nalkaya <notifications@github.com> wrote:

> @agronick <https://github.com/agronick> sorry for late reply Kyle, i've
> just had a time to review the PR.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/sardok/aiogear/pull/5#issuecomment-401780915>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AB8pv1QnpVM5Bp3yd7WH-rsbCyLcjQMvks5uCgr0gaJpZM4U51gZ>
> .
>

2018-07-10 08:15 UTC, sardok commented
@agronick Created PR6 with additional fixes.

2018-07-10 08:15 UTC, closed without merging